spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/poc
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
  batch:
       jdbc:
         initialize-schema: always
       job:
          enabled: true
          name: furniture-job
  flyway:
       enabled: true
       baseline-on-migrate: true





